name: Publish to package registries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Install dependencies
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies with pnpm
        run: pnpm install

      # Update version in code
      - name: Replace version in Version.ts to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" src/util/Version.ts

      # Build and test
      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
      
      # Final touches
      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json

      # Publish to registries
      - name: Publish package on GitHub
        run: pnpm publish . --access=restricted --no-git-checks --report-summary
        env:
          sToken: ${{ secrets.TECSAFE_PACKAGES_READ_WRITE }}
